### ISSUE TITLE
Internal Server Error when importing Juniper log

### ISSUE THREAD

**Issue by 831Mark** [Vadims06/topolograph-docker#1]
I am seeing an internal server error whenever I try to import a log file from a Juniper MX104.  I can confirm the program is working correctly, as I have no problem importing demoLSB.txt from you repository.

The following error is attempting to import from a .txt file of the output of "show ospf database router extensive | no-more"

I've attached the output of the log from Flask, with IP address masked for security.

FWIW, I am seeing the same Internal Server Error issue at topolograph.com.

[flaskerror.log](https://github.com/Vadims06/topolograph-docker/files/5461037/flaskerror.log)

**Comment by Vadims06** [comment]
Hi @831Mark, it seems that there is a DR in your network, but you saved only LSA1 (database router) output, but it necessary to save database network and keep it in the same file. Write me if it was helpful for you.

**Comment by 831Mark** [comment]
Oh, it wasn't clear from documentation that I needed to import LSA1, LSA2, and LSA5 all at once.  Having done that, I'm getting a new error. Log attached.  (I am also seeing an error like this when trying to use Napalm, btw).
[flaskerror2.log](https://github.com/Vadims06/topolograph-docker/files/5461122/flaskerror2.log)

**Comment by 831Mark** [comment]
I am happy to share my router export with you, but I'd rather not post it here, btw.

**Comment by Vadims06** [comment]
> I am happy to share my router export with you, but I'd rather not post it here, btw.

@831Mark I will be happy to help. Could you please send me the output to admin@topolograph.com

**Comment by Vadims06** [comment]
> Oh, it wasn't clear from documentation that I needed to import LSA1, LSA2, and LSA5 all at once. Having done that, I'm getting a new error. Log attached. (I am also seeing an error like this when trying to use Napalm, btw).
> [flaskerror2.log](https://github.com/Vadims06/topolograph-docker/files/5461122/flaskerror2.log)

I should mention it my documentation, that LSA 1 and LSA2 is mandatory, LSA 5 is optional

**Comment by 831Mark** [comment]
Sent the file.  Thanks!

**Comment by 831Mark** [comment]
It's something in LSA5.  I just successfully loaded LSA1 and LSA2.

**Comment by Vadims06** [comment]
> It's something in LSA5. I just successfully loaded LSA1 and LSA2.

Yes... silly mistake. Fixed it on topolograph site ( you can upload a file with LSA 5). Later I will add this fix in doker version.
Many thanks!

**Comment by 831Mark** [comment]
Thank you!
