### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by cubeslinger** [Vadims06/topolograph-docker#2]
Hi, more than an issue this is a feature or help request, i'm trying to run you dockerized app on linux:

Archlinux: Linux cube 5.13.7-arch1-1 #1 SMP PREEMPT Sat, 31 Jul 2021 13:18:52 +0000 x86_64 GNU/Linux
Docker: Docker version 20.10.7, build f0df35096d

but it stops at the pull phase with something like this multiple times:

docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

i read that you support Windows and Macs, but i'm asking: would it be possible to extend support to linux machines?

I'm one of the administrators of an HP/Aruba OSPF network and i could help integrate support for this vendor if you're interested.

Best regards, Marco Barbieri.

**Comment by Vadims06** [comment]
Hi @cubeslinger, this error happens when docker service is not running. Please check the status as well as try to run hello-world image
```
$ docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.
```

Regarding HP/Aruba support - this is great! Please join this thread [HP support](https://github.com/Vadims06/topolograph/issues/16)

**Comment by cubeslinger** [comment]
Hi,

   thank you for answering and sorry for me being dumber than usual, i blame it on monday.
   Now i'll try to understand what data you do need for HP/Aruba integration.

   Thanks again Marco Barbieri.

**Comment by cubeslinger** [comment]
Hi,

   guessing from "textfsm_templates" i think the output from these two commands can help, let me know if i'm on track and/or what else is needed and please remember that files have been lightly anonymized.

   The commands used were:

   #sh ip ospf_external-link-state detail
   #sh ip ospf link-state detail

   Regards, Marco Barbieri.

**Comment by Vadims06** [comment]
@cubeslinger, you are right. These commands seem to describe LinkState DataBase of OSPF in HP. Could you please sent me the output on admin at topolograph.com and also provide the topology diagram ( a plot in Paint is enough ) =)
